title: Yuxin Wen
logo: /assets/img/profile.png
description: ywen@umd.edu
show_downloads: false
google_scholar: https://scholar.google.com/citations?user=oUYfjg0AAAAJ&hl=en
theme: jekyll-theme-minimal

