title: Yuxin Wen
email: ywen@umd.edu
logo: /assets/img/final.jpeg
description:
show_downloads: false
google_scholar: https://scholar.google.com/citations?user=oUYfjg0AAAAJ&hl=en
theme: jekyll-theme-minimal

